name: NSE Exchange Filings Bot

on:
  workflow_dispatch:   # manual trigger
  schedule:
    # Fast checks during market hours (09:15–15:30 IST → 03:45–10:00 UTC)
    - cron: "*/5 3-10 * * 1-5"

    # Slower checks outside market hours (every 30 minutes on weekdays)
    - cron: "*/30 * * * 1-5"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NSE Exchange Filings Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python exchangefilings.py || echo "⚠️ Bot exited with error"
