name: NSE Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 minutes
  workflow_dispatch:         # allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run NSE filings bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python exchangefilings.py || echo "⚠️ Bot exited with error"

      - name: Commit user data
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add users.json || true
          git commit -m "Update users.json" || echo "No changes to commit"
          git push || echo "No changes pushed"

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: bot-logs
          path: bot.log
