name: NSE Filing Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # run every 5 mins
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run NSE Bot
        run: python exchangefilings.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.8372701249:AAFbzxUMHM_IXFJttgp_0vepx1h24CbuLF0 }}

      - name: Commit & Push users.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add users.json || echo "No changes to commit"
          git commit -m "Update users.json" || echo "No changes to commit"
          git push
